feat: Add comment after LICENSE Check
  Add comment after LICENSE Check

Log: Add comment after LICENSE Check

diff --git a/.github/workflows/license-check.yml b/.github/workflows/license-check.yml
--- a/.github/workflows/license-check.yml
+++ b/.github/workflows/license-check.yml
@@ -3,11 +3,34 @@ on: workflow_call
 
 jobs:
   Check-License:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v3
-      - uses: fsfe/reuse-action@v1.2.0
+      - name: Install reuse
+        run: sudo apt install reuse
+      - name: License Check
+        id: lcheck
+        run: reuse lint
         continue-on-error: true
+      - name: Generate Reports
+        if: steps.lcheck.outcome != 'success'
+        run: mkdir output;reuse lint > output/results.txt || true
+      - name: Generate License pass Reports
+        if: steps.lcheck.outcome == 'success'
+        run: mkdir output;echo "All right about License Check!" > output/results.txt || true
+      - uses: actions/upload-artifact@v3.1.0
+        with:
+          name: results
+          path: output
+      - uses: actions/download-artifact@v3.0.0
+        with:
+          name: results
+      - name: comment PR
+        uses: machine-learning-apps/pr-comment@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          path: output/results.txt
   Check-README:
     runs-on: ubuntu-latest
     steps:
@@ -15,15 +38,34 @@ jobs:
       - name: Install zsh
         run: sudo apt install zsh
       - name: README.md Check
+        id: rcheck
+        continue-on-error: true
         run: if [ ! -f "README.md" ];then echo "missing README.md";return 1;fi
         shell: zsh {0}
-  Check-README_zh_CN:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install zsh
-        run: sudo apt install zsh
+      - name: Generate README Check Reports
+        if: steps.rcheck.outcome != 'success'
+        run: mkdir output||true; echo "missing README.md" > output/results.txt
       - name: README.zh_CN.md Check
+        id: zhrcheck
         continue-on-error: true
         run: if [ ! -f "README.zh_CN.md" ]; then echo "missing README.zh_CN.md";return 1;fi
         shell: zsh {0}
+      - name: Generate README zh_CN Check Reports
+        if: steps.zhrcheck.outcome != 'success'
+        run: mkdir output||true; echo "missing README.zh_CN.md" >> output/results.txt
+      - name: Generate Reports
+        if: steps.rcheck.outcome == 'success' && steps.zhrcheck.outcome == 'success'
+        run: mkdir output||true; echo "All right about README Check" >> output/results.txt
+      - uses: actions/upload-artifact@v3.1.0
+        with:
+          name: results
+          path: output
+      - uses: actions/download-artifact@v3.0.0
+        with:
+          name: results
+      - name: comment PR
+        uses: machine-learning-apps/pr-comment@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          path: output/results.txt
